name: Comment on assigned issue

on:
  issues:
    types:
      - assigned

jobs:
  comment-on-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add comment
        uses: actions/github-script@v6
        with:
          script: |
            const issue = github.issues.get(github.event.issue.number);
            const assignee = issue.assignees[0];

            github.issues.createComment(issue.number, {
              body: `Hi @${assignee.login},

              You have been assigned to this issue. Please let me know if you have any questions.

              Thanks,
              [Your name]`
            });

