name: Comment on assigned issue

on:
  issues:
    types:
      - assigned

jobs:
  comment-on-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add comment
        uses: peter-evans/create-or-update-comment@v5f728c3dae25f329afbe34ee4d08eef25569d79f
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hi @{{ github.event.assignees[0].login }},

            You have been assigned to this issue. Please let me know if you have any questions.

            Thanks,
            [Your name]
