name: Assign Issue

on:
  schedule:
    - cron: 0 0 * * *
  issue_comment:
    types: [created]
  workflow_dispatch:

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign the user or unassign stale assignments
        uses: takanome-dev/assign-issue-action@v2.1.1
        with:
          github_token: '${{ secrets.VIVEK_TOKEN }}'
          # trigger: '/assign-me' # you can change the default trigger to something else
          # required_label: # if present, the issue must have this label to be assigned
          # assigned_label: 📍 Assigned
          # days_until_unassign: 3
          # learn more about the inputs below ⬇
