name: Label issues

on:
  pull_request_target:
    types:
      - closed

jobs:
  if_merged:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Add Hacktoberfest label
        if: github.event.pull_request.merged == true
        uses: actions/github-script@v6
        with:
          script: |
            github.issues.addLabels({
              issue_number: github.event.pull_request.number,
              owner: github.repository_owner,
              repo: github.repository,
              labels: ["hacktoberfest"]
            })
