name: Label Pull Requests

on:
  pull_request_target:
    types:
      - closed

jobs:
  label:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Label PR
        uses: srvaroa/labeler@v0.8
        with:
          config_path: .github/labeler_configuration.yml
        env:
          GITHUB_TOKEN: ${{ secrets.VIVEKS_TOKEN }}
